version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    container_name: discovery-weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      # Query settings
      QUERY_DEFAULTS_LIMIT: 25

      # Authentication (disabled for local development)
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'

      # Persistence
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'

      # Enable modules
      ENABLE_MODULES: 'text2vec-transformers'

      # Module configuration
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'

      # Transformers module configuration
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'

      # Cluster configuration
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    networks:
      - weaviate_network
    depends_on:
      - t2v-transformers

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    container_name: discovery-t2v-transformers
    environment:
      ENABLE_CUDA: '0'  # Set to '1' if you have GPU support
    restart: unless-stopped
    networks:
      - weaviate_network

volumes:
  weaviate_data:
    driver: local

networks:
  weaviate_network:
    driver: bridge
